### ISSUE TITLE
Issue displaying negative amount with six digits

### ISSUE THREAD

**Issue by Daniel-Diaz** [alx741/currencies#1]
Hey I have tried your library and got some issues displaying negative amounts.

Example output:

```
-,129,553.53
```

Note the comma after the minus sign.

In a rush right now, but I am guessing it happens with any negative amount with `3xN` digits.

Thanks!

**Comment by alx741** [comment]
Thanks for reporting it.
A bit busy now, but will take a look at it as soon as i can.

**Comment by alx741** [comment]
I think that should do it. Please let me know if there is any other issue.

New Hackage release: `0.1.1.1`
